set(SOURCES
	include/Common.h
	include/Papyrus/Functions/ActiveEffect.h
	include/Papyrus/Functions/Actor.h
	include/Papyrus/Functions/ActorBase.h
	include/Papyrus/Functions/ActorValue.h
	include/Papyrus/Functions/Ammo.h
	include/Papyrus/Functions/Armor.h
	include/Papyrus/Functions/Array.h
	include/Papyrus/Functions/Book.h
	include/Papyrus/Functions/Cell.h
	include/Papyrus/Functions/CombatStyle.h
	include/Papyrus/Functions/Debug.h
	include/Papyrus/Functions/Faction.h
	include/Papyrus/Functions/Form.h
	include/Papyrus/Functions/Game.h
	include/Papyrus/Functions/Keyword.h
	include/Papyrus/Functions/LeveledList.h
	include/Papyrus/Functions/Location.h
	include/Papyrus/Functions/Math.h
	include/Papyrus/Functions/ObjectReference.h
	include/Papyrus/Functions/PlayerCharacter.h
	include/Papyrus/Functions/Projectile.h
	include/Papyrus/Functions/String.h
	include/Papyrus/Functions/UI.h
	include/Papyrus/Functions/VATS.h
	include/Papyrus/Functions/Weapon.h
	include/Papyrus/Functions/Weather.h
	include/Papyrus/Utilities/ActorUtils.h
	include/Papyrus/Utilities/LeveledListUtils.h
	include/Papyrus/Manager.h
	src/PCH.h
	src/main.cpp
	src/Papyrus/Utilities/ActorUtils.cpp
	src/Papyrus/Utilities/LeveledListUtils.cpp
	src/Papyrus/Manager.cpp
)
